

# Disable the newline at the start of the prompt
add_newline = false

_format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$golang\
$java\
$python\
$rust\
$swift\
$nix_shell\
$memory_usage\
$gcloud\
$env_var\
$cmd_duration\
$custom\
$line_break\
$time\
$status\
$character"""

format = """
$hostname\
$directory\
$git_branch\
$git_status\
$character
"""

[hostname]
format =  "[$user@$hostname](bold green):"

[git_status]
format = '[$all_status$ahead_behind]($style)'
modified = "*"

[git_branch]
format = "@[$branch]($style)"
style = "bold green"

[character]
success_symbol = '\$'
error_symbol = '[\$](bold red)'

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold blue"