format = """
$cmd_duration\
[$username@$hostname](bold green):$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character\
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[hostname]
ssh_only = false
format = "[$hostname](bold green)"
disabled = false

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[character]
success_symbol = "[\\$](bold blue)"
error_symbol = "[\\$](bold red)"

[directory]
style = "bold blue"
format = "[$path]($style)[$read_only]($read_only_style)"

[cmd_duration]
format = "took [$duration]($style)\n"
show_notifications = true
min_time = 2_000

[git_branch]
format = "@[$branch]($style)"
symbol = ""
only_attached = true

[git_commit]
format = "[\\($hash$tag\\)]($style)"
commit_hash_length = 7

[git_status]
format = '([$all_status$ahead_behind]($style))'
disabled = true

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\)'
